spring:
  application:
    name: Jasypt-example

  datasource:
     url: jdbc:mysql://db.sewoomch.com:3306/dbsewoomch?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
     username: ENC(ShdZigbYUELWeDvvtSi6aXafgl9HNEMV)
     password: ENC(mqnPTyJdJloXOqte4GzizJ7Lo+f9v8lY)
     driver-class-name: com.mysql.cj.jdbc.Driver